### PR TITLE
Adopt gradle as build tool and update all dependencies to latest

### PR DESCRIPTION
**Pull request by gregallen**
This plugin is blocked by some companies as the dependency jars are old and contain security vulnerabilities.

This pull request adopts gradle as a build tool and bumps dependencies to latest version

Note that I'm not really able to test the plugin signing and publication steps, but hopefully that's fairly easy to do

Plugin builds and runs fine in intellij for me

### CODE REVIEW

**Comment by krasa** [comment]
How is your hotswapping? Does a simple change take 20s? https://github.com/JetBrains/gradle-intellij-plugin/issues/459

**Comment by gregallen** [comment]
It's fine, but normally I set the project to build and run with intellij, which should be equivalent to your current build/run/hot-replace cycle. Gradle then mostly used for dependency management and running tests, and intellij automatically syncs you project & module settings from gradle. This works very well in my experience.

It is also excellent in that you can easily have the tests run automatically as a github action whenever you push - I've included the set-up for this in my pull request. You likely just have to enable the Actions feature in this github project. You can see it run in mine here: https://github.com/gregallen/GrepConsole/actions

This also means that you can enable github dependabot to update the dependencies automatically and have them automatically tested for compatability by the action - I just literally used this to bump junit version on my fork

**Comment by gregallen** [comment]
image

**Comment by gregallen** [comment]
Running clean & instrumentCode takes 8 secs for me:
```
BUILD SUCCESSFUL in 8s
13 actionable tasks: 13 executed
13:57:36: Execution finished 'clean instrumentCode --no-build-cache'.
```

**Comment by krasa** [comment]
I understand the benefits, but I am talking about hot swap which can take more than 30s, depending on how many classes are loaded, which is just terrible:

q

**Comment by krasa** [comment]
> image

That seems to do the trick :-)

**Comment by krasa** [comment]
Thank you! That is quite awesome.

**Pull request merged**
